# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
#    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Setup nodeJS
      uses: actions/setup-node@v1
      with: 
        node-version: ${{matrix.node-version}}
#     - name: clone the repo
#       run: git clone https://github.com/sumangala028/learn-github-action.git
#     - name: Go to the project folder
#       run: cd ./hello-world
    - name: install dep
      working-directory: ./hello-world
      run: npm install
    - name: Build the files
      working-directory: ./hello-world
      run: npm run build
    - name: Clone a repo
      run: |
        git config --global user.email "sumangala028@gmail.com"
        git config --global user.name "sumangala028"
        
        git clone https://github.com/sumangala028/sample-repo.git
        
        cd sample-repo
        git checkout -b sampleBranch
        echo "" >> README.md
        echo "Hello World!" >> README.md
        
        git add --all
        git commit -m "README updated."
        sudo git push origin -f sampleBranch
                
        sudo snap install hub --classic
        hub pull-request -m "Update Readme" -b sumangala028:master -h sumangala028:sampleBranch
        echo 'Successfully sent a pull request to sample.git'
        
        
        
