# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Setup nodeJS
      uses: actions/setup-node@v1
      with: 
        node-version: ${{matrix.node-version}}
#     - name: clone the repo
#       run: git clone https://github.com/sumangala028/learn-github-action.git
#     - name: Go to the project folder
#       run: cd hello-world
    - name: Build the files
      run: npm build

    
      
      
 
